function createfigure(X1, Y1, X2, Y2, X3, Y3)
%Esta funcion se ha obtenido al exportar la figura desde la ventana Figure
%tras modificar sus propiedades (color de los puntos, nombre de ejes,etc)
%CREATEFIGURE1(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 14-Apr-2020 17:15:20

% Create figure
figure1 = figure('NumberTitle','off','Name','f(x) = sin(x)');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create plot
plot(X2,Y2,'MarkerEdgeColor',[0 0 1],'MarkerSize',11,'Marker','.',...
    'LineStyle','none');

% Create plot
plot(X3,Y3,'MarkerEdgeColor',[0 1 0],'MarkerSize',11,'Marker','.',...
    'LineStyle','none');

% Create ylabel
ylabel('sin(x)','Color',[0 0 1]);

% Create xlabel
xlabel('x','Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-13 13]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2 2]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'TickLabelInterpreter','latex','XAxisLocation','origin','XGrid',...
    'on','XTick',...
    [-12.5663706143592 -10.9955742875643 -9.42477796076938 -7.85398163397448 -6.28318530717959 -4.71238898038469 -3.14159265358979 -1.5707963267949 0 1.5707963267949 3.14159265358979 4.71238898038469 6.28318530717959 7.85398163397448 9.42477796076938 10.9955742875643 12.5663706143592],...
    'XTickLabel',...
    {'$-4\pi$','$\frac{-7\pi}{2}$','$-3\pi$','$\frac{-5\pi}{2}$','$-2\pi$','$\frac{-3\pi}{2}$','$-\pi$','$\frac{-\pi}{2}$','$0$','$\frac{\pi}{2}$','$\pi$','$\frac{3\pi}{2}$','$2\pi$','$\frac{5\pi}{2}$','$3\pi$','$\frac{7\pi}{2}$','$4\pi$'},...
    'YAxisLocation','origin','YGrid','on');
