function ondaSierra(X1, Y1)
%para ver exactamente la figura representada para las series de Fourier
%onda de sierra, usar esta función. Ha sido exportada desde la ventana de
%Figure tras haber modificado propiedades del plot
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Apr-2020 00:43:32

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth', 1);

% Create ylabel
ylabel('x(t)','Color',[0 0 1]);

% Create xlabel
xlabel('t','Color',[0 0 1]);

% Create title
title({'Función onda de sierra de periodo T = 1',''},...
    'Color',[1 0.411764705882353 0.16078431372549]);

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XAxisLocation','origin');
